app/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length, Regexp


class LoginForm(FlaskForm):
    username = StringField('Username', [
        Required(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                          'Usernames must have only letters, '
                                          'numbers, dots or underscores')])
    password = PasswordField('Password', [Required()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log In')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy

from flask_login import LoginManager
from flask_pagedown import PageDown


from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
pagedown = PageDown()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'login.index'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    print(">>> config db : ", config[config_name].SQLALCHEMY_DATABASE_URI)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)

    # from .main import main as main_blueprint
    # app.register_blueprint(main_blueprint)
    #
    # from .auth import auth as auth_blueprint
    # app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .views.main import main_bp
    app.register_blueprint(main_bp)

    from .views.login import login
    app.register_blueprint(login, url_prefix='/login')

    from .views.todo_lists import todo_list
    app.register_blueprint(todo_list, url_prefix='/todo_list')

    return app

app/api_1_0/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import errors, todo_items

app/views/account.py
from flask import Blueprint, flash, jsonify, render_template, request, url_for

from app.forms import RegisterForm
from app.model import User, db

register = Blueprint('register', __name__)


@register.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        return render_template(
            'register.html', login_url=url_for('login.index'), register_url=url_for('register.index'))
    else:
        return register_validate()


def register_validate():
    form = RegisterForm()
    if form.validate_on_submit():
        input_username = request.json.get('username', None)
        input_password = request.json.get('password', None)
        input_email = request.json.get('email', None)
        user = User.query.filter_by(username=input_username).first()
        if user is not None:
            flash('User {} has been registered, please change it.'.format(input_username))
        elif User.query.filter_by(email=input_email).first() is not None:
            flash('Email {} has been registered, please change it.'.format(input_email))
        else:
            flash('Success to register, please enjoy your journey!')
            db.session.add(User(username=input_username, password=input_password, email=input_email))
            db.session.commit()
            return jsonify({'next_url': url_for('login.index')})
    return jsonify({'next_url': url_for('register.index')})

app/views/login.py
from datetime import timedelta

from flask import Blueprint, flash, jsonify, redirect, render_template, request, session, url_for
from flask_login import login_user, logout_user, login_required

from app import get_app, login_manager
from app.forms import LoginForm
from app.model import User

login = Blueprint('login', __name__)


@login.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        return render_template('login.html', login_url=url_for('login.index'), register_url=url_for('register.index'))
    else:
        return login_validate()


def login_validate():
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    remember = request.json.get('remember', False)
    form = LoginForm()
    valid = form.validate()
    print(form.errors)
    if valid:
        user = User.query.filter_by(username=username).first()
        if user and user.verify_password(pwd=password):
            login_user(user, remember)
            session.permanent = True
            app = get_app()
            app.permanent_session_lifetime = timedelta(minutes=app.config['SESSION_LIFETIME'])
            return jsonify({'next_url': url_for('todo_list.index')})
        else:
            flash('Invalid username or password, please try again.')
    return jsonify({'next_url': url_for('login.index')})


@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))


@login.route('/logout', methods=['GET'])
@login_required
def logout():
    flash('You were logged out')
    logout_user()
    return redirect(url_for('login.index'))

app/views/main.py
from flask import Blueprint, redirect, url_for

main_bp = Blueprint('main', __name__)


@main_bp.route('/', methods=['GET'])
def index():
    """Redirect home page to login page."""
    return redirect(url_for('login.index'))

app/views/todo_lists.py
from datetime import datetime

from flask import Blueprint, flash, redirect, request, render_template, url_for
from flask_login import login_required

from app.model import Todo, db

todo_list = Blueprint('todo_list', __name__)


@todo_list.route('/', methods=['GET', 'POST'])
@login_required
def index():
    items = Todo.query.all()
    return render_template('todo_list.html', entries=items, current_time=datetime.utcnow())


@todo_list.route('/add', methods=['POST'])
@login_required
def add_item():
    td = Todo(request.form['title'])
    db.session.add(td)
    db.session.commit()

    flash('new entry added successfully')
    return redirect(url_for('todo_list.index'))


@todo_list.route('/del/<int:id>', methods=['POST'])
@login_required
def del_item(id):
    print("delete item %d" % id)

    td = Todo.query.filter_by(id=id).first()
    db.session.delete(td)
    db.session.commit()

    return redirect(url_for('todo_list.index'))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Todo list{% endblock %}

{% block head %}
{{ super() }}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

<link rel="icon" href="{{ url_for('static', filename='fav.ico') }}" type="image/x-icon">
{% endblock %}

{% block content %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('login.index') }}">log in</a>
        {% else %}
        <a href="{{ url_for('login.logout') }}">log out</a>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Todo list - Login{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>Login</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
        <br>
    </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Flasky - Register{% endblock %}

{% block page_content %}
<h2 id="login-header" class="ui center aligned header register">Create your account</h2>
<div id="message-container" style="text-align: center;">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" style="text-align: center; display: inline-block; margin-bottom: 2px">
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<div id="register">
    <!-- <register-form login_url="{{ login_url }}" register_url="{{ register_url }}">
    </register-form> -->
    <register-form login_url="{{ login_url }}" register_url="{{ register_url }}">
    </register-form>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript" src="/static/js/register.js"></script>
{% endblock %}

app/templates/test.html
{% extends "bootstrap/base.html" %}

{% block title %}Flask test page{% endblock %}

{% block content %}

	{% block nav %}
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Brand</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
		        <li><a href="#">Link</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="#">One more separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		      <form class="navbar-form navbar-left">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>
		      </form>
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="#">Link</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
	{% endblock %}

	<ul class="nav nav-tabs">
	  <li role="presentation" class="active"><a href="#home" aria-controls="home" data-toggle="tab" role="tab">Home</a></li>
	  <li role="presentation"><a href="#profile" aria-controls="profile" data-toggle="tab" role="tab">Profile</a></li>
	  <li role="presentation"><a href="#message" aria-controls="message" data-toggle="tab" role="tab">Messages</a></li>
	</ul>

	<!-- Tab panes -->
  	<div class="tab-content">
    	<div role="tabpanel" class="tab-pane fade in active" id="home">
    		<ul>
			    <li><a href="/">Home</a></li>
				<li><a href="contacts">Contact</a></li>
				<li><a href="/words/dog/rhymes">rhymes</a></li>
		    <ul>

    	</div>
    	<div role="tabpanel" class="tab-pane" id="profile">
    		<h4>Profile</h4>

    	</div>
    	<div role="tabpanel" class="tab-pane" id="message">
    		<h4>Message</h4>
    	</div>
    </div>

    {% endblock %}

app/templates/todo_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Todo list{% endblock %}

{% block page_content %}

<p>The local date and time is {{ moment(current_time).format('LLL') }}.</p>

{% if current_user.is_authenticated %}
<form action="{{ url_for('todo_list.add_item') }}" method="post" class="add-entry">
    <dl>
        <dt>I'm going to :
        <dd><textarea name="title" rows="5" cols="40"></textarea>
        <dd><input type="submit" class="btn btn-success" value="Add">
    </dl>
</form>
{% endif %}


<div class="list-group">
    <tr>
        <th>What to do ?</th>
    </tr>

    {% for item in entries %}
    <p>
        <class container>
            <li class="list-group-item"> {{item.title}}</li>

            <form action="{{url_for('todo_list.del_item', id=item.id)}}" method="post" class="remove-entry">
                <input type="submit" class="btn btn-danger btn-xs" value="delete">
            </form>
        </class>
    </p>
    {% endfor %}

</div>


{% endblock %}